### ISSUE TITLE
[BUG] - Container cannot recover from unexpected exit

### ISSUE THREAD

**Issue by muskette** [tprasadtp/protonvpn-docker#101]
### Version of `protonvpn-docker`

>=5.0.0

### Credential & Plan

- [X] I have verified that my VPN credentials are valid
- [X] I am using OpenVPN credentials and **not** my proton account credentials.
- [X] I have verified that the servers I am trying to connect to are available under my plan.

### System Architecture

amd64 / arm64

### Running on a NAS?

No

### Container Runtime

Docker with defaults

### Version of Kubernetes

NA

### Version of docker/podman runtime

Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-30-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.509GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### Troubleshooting

- [X] I have tried steps mentioned in [TROUBLESHOOTING](https://tprasadtp.github.io/protonvpn-docker/#/troubleshooting)
- [X] I am using latest version of the docker image

### Relevant log output

```shell
protonvpn    | 2022-03-06 16:12:03+00:00 [INFO    ] Checking orphaned openvpn process 
protonvpn    | 2022-03-06 16:12:03+00:00 [INFO    ] This appears to be a fresh start! 
protonvpn    | 2022-03-06 16:12:03+00:00 [NOTICE  ] Using fastest available P2P server 
protonvpn    | Traceback (most recent call last):
protonvpn    |   File "/usr/local/bin/protonvpn", line 8, in <module>
protonvpn    |     sys.exit(main())
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 73, in main
protonvpn    |     cli()
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 123, in cli
protonvpn    |     connection.feature_f(4, protocol)
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 212, in feature_f
protonvpn    |     disconnect(passed=True)
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 344, in disconnect
protonvpn    |     manage_dns("restore")
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 612, in manage_dns
protonvpn    |     oldhash = get_config_value("metadata", "resolvconf_hash")
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/utils.py", line 123, in get_config_value
protonvpn    |     return config[group][key]
protonvpn    |   File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
protonvpn    |     raise KeyError(key)
protonvpn    | KeyError: 'resolvconf_hash'
protonvpn    | 2022-03-06 16:12:03+00:00 [ERROR   ] There is no OpenVPN Process!! 
protonvpn    | 2022-03-06 16:12:03+00:00 [WARNING ] Reconnecting... 
protonvpn    | [!] Couldn't find a previous connection
protonvpn    | [!] Please connect normally first
protonvpn    | 2022-03-06 16:12:04+00:00 [ERROR   ] Failed to reconnect 
protonvpn    | 2022-03-06 16:12:04+00:00 [WARNING ] Trying with a fresh connection! 
protonvpn    | 2022-03-06 16:12:04+00:00 [NOTICE  ] Using fastest available P2P server 
protonvpn    | Traceback (most recent call last):
protonvpn    |   File "/usr/local/bin/protonvpn", line 8, in <module>
protonvpn    |     sys.exit(main())
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 73, in main
protonvpn    |     cli()
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 123, in cli
protonvpn    |     connection.feature_f(4, protocol)
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 212, in feature_f
protonvpn    |     disconnect(passed=True)
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 344, in disconnect
protonvpn    |     manage_dns("restore")
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 612, in manage_dns
protonvpn    |     oldhash = get_config_value("metadata", "resolvconf_hash")
protonvpn    |   File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/utils.py", line 123, in get_config_value
protonvpn    |     return config[group][key]
protonvpn    |   File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
protonvpn    |     raise KeyError(key)
protonvpn    | KeyError: 'resolvconf_hash'
```

### Any additional info

Found this after my docker host unexpectedly rebooted.
Seems to be the same issue as here:
https://github.com/Rafficer/linux-cli-community/issues/263

Reproducing:
I eventually triggered this error consistently by running ```docker kill``` on the container. When starting it again, it runs into this error.
I've recreated this on both my amd64 laptop & arm64 raspi with 5.0.0, 5.1.2 & 5.2.0

Manual Resolution:
Either ```exec``` into the container and manually ```rm ~/.pvpn-cli/resolv.conf.backup``` or
destroy and rebuild the container

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by fabrizio5680** [comment]
Specifically came to raise this issue and found the exact same, including same where I found fix and the manual resolution which worked while the container is running and trying to reconnect doing a `rm ~/.pvpn-cli/resolv.conf.backup` will resolve it immediately on next retry.

**Comment by muskette** [comment]
Many thanks on the swift fix!
